### ISSUE TITLE
Redis ECONNRESET and "rediss" warning

### ISSUE THREAD

**Issue by markstur** [IBM/alexa-skill-watson-conversation#30]
Redis is complaining about "rediss" -- that is only a warning and probably not the error, but then there is an ECONNRESET.  So for some reason we are not able to maintain a connection to work with Redis.

                 {"error":"The action did not produce a valid response and exited unexpectedly."},
                  "success":false,
                  "status":"action developer error"},
                  "end":1520863837705,
                  "logs":[
                  "2018-03-12T14:10:37.299684781Z stdout: Begin action",
                  "2018-03-12T14:10:37.636605477Z stdout: Connected to Watson Conversation",
                  "2018-03-12T14:10:37.640980509Z stderr: node_redis: WARNING: You passed \"rediss\" as protocol instead of the \"redis\" protocol!",
                  "2018-03-12T14:10:37.644396496Z stdout: Connected to Redis",
                  "2018-03-12T14:10:37.644415148Z stdout: sessionId: SessionId.bbda3171-5438-4d2b-baff-1e9210cce63b",
                  "2018-03-12T14:10:37.692747814Z stderr: events.js:160",
                  "2018-03-12T14:10:37.69276912Z  stderr: throw er; // Unhandled 'error' event",
                  "2018-03-12T14:10:37.692781985Z stderr: ^",
                  "2018-03-12T14:10:37.692795232Z stderr: ",
                  "2018-03-12T14:10:37.692802114Z stderr: Error: Redis connection to portal1213-8.bmix-dal-yp-06298201-d5d6-4bf3-9ab3-5b9a4d8ec887.thomas-suedbroecker-de-ibm-com.composedb.com:37151 failed - read ECONNRESET",
                  "2018-03-12T14:10:37.692811179Z stderr: at exports._errnoException (util.js:1020:11)",
                  "2018-03-12T14:10:37.692817643Z stderr: at TCP.onread (net.js:568:26)",
                  "2018-03-12T14:10:52.134Z       stderr: There was an issue while collecting your logs. Data might be missing."

**Comment by markstur** [comment]
Current code does not work with TLS (which is now the default for Compose for Redis).

WORKAROUND:  When you create the services use the pulldown to specify TLS = FALSE.

**Comment by markstur** [comment]
Updated the problem to clarify that it is related to the TLS setting.
The new default TLS=True does not work w/ the current code.
Will update with documentation.
