### ISSUE TITLE
stderr: { Error: Resource not found

### ISSUE THREAD

**Issue by MazenSalama** [IBM/alexa-skill-watson-conversation#39]
what is the problem ?

/alexa-skill-watson-conversation# bx wsk activation list -l1 | tail -n1 | cut -d ' ' -f1 | xargs bx wsk activation logs
2018-10-16T13:27:01.873285435Z stdout: Begin action
2018-10-16T13:27:02.082137332Z stdout: Connected to Watson Conversation
2018-10-16T13:27:02.088706799Z stdout: Connected to Redis
2018-10-16T13:27:02.088730783Z stdout: sessionId: amzn1.echo-api.session.0fa3d3b2-a69b-4a3c-8a43-4578bf8ba8d4
2018-10-16T13:27:02.102072117Z stdout: context:
2018-10-16T13:27:02.103601573Z stdout: {}
2018-10-16T13:27:02.103946337Z stdout: WORKSPACE_ID: 6bd637f6-1074-4d94-855e-d0d86f4f7b75
2018-10-16T13:27:02.103955002Z stdout: Input text: hi
2018-10-16T13:27:02.463362996Z stderr: { Error: Resource not found
2018-10-16T13:27:02.46341617Z  stderr: at Request._callback (/nodejsAction/NjP0Z1G0/node_modules/watson-developer-cloud/lib/requestwrapper.js:102:21)
2018-10-16T13:27:02.463428631Z stderr: at Request.self.callback (/nodejsAction/NjP0Z1G0/node_modules/watson-developer-cloud/node_modules/request/request.js:185:22)
2018-10-16T13:27:02.463435974Z stderr: at emitTwo (events.js:106:13)
2018-10-16T13:27:02.463442117Z stderr: at Request.emit (events.js:191:7)
2018-10-16T13:27:02.463448427Z stderr: at Request.<anonymous> (/nodejsAction/NjP0Z1G0/node_modules/watson-developer-cloud/node_modules/request/request.js:1157:10)
2018-10-16T13:27:02.463456288Z stderr: at emitOne (events.js:96:13)
2018-10-16T13:27:02.463462308Z stderr: at Request.emit (events.js:188:7)
2018-10-16T13:27:02.463466539Z stderr: at Gunzip.<anonymous> (/nodejsAction/NjP0Z1G0/node_modules/watson-developer-cloud/node_modules/request/request.js:1079:12)
2018-10-16T13:27:02.463471236Z stderr: at Gunzip.g (events.js:292:16)
2018-10-16T13:27:02.46347533Z  stderr: at emitNone (events.js:91:20)
2018-10-16T13:27:02.4634792Z   stderr: code: 404,
2018-10-16T13:27:02.463483373Z stderr: error: 'Resource not found',
2018-10-16T13:27:02.463487402Z stderr: 'x-global-transaction-id': '7ecac92c5bc5e72640cc905f' }
2018-10-16T13:27:02.463684232Z stderr: Caught error:
2018-10-16T13:27:02.463817132Z stdout: Error talking to Watson.

**Comment by markstur** [comment]
Most likely your workspace ID is not correct. Make sure the one you see in the log is correct for your workspace.

If that isn't it, double-check the credentials and URL and try your conversation in the tool to make sure it isn't just rate-limiting due to plan limits.
